INSERT INTO TipoDocumento VALUES('Cedula De Ciudadania')
INSERT INTO TipoDocumento VALUES('Cedula Extranjera')
INSERT INTO TipoDocumento VALUES('Tarjeta de identidad')

INSERT INTO Especialidades VALUES('Anesteiologo')
INSERT INTO Especialidades VALUES('Radiologo')
INSERT INTO Especialidades VALUES('Cardiologo')
INSERT INTO Especialidades VALUES('Cirujano')
INSERT INTO Especialidades VALUES('General')

INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 1')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 2')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 3')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 4')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 5')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 6')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 7')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 8')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 9')
INSERT INTO Sede VALUES('3202884882', 'Calle Falsa 123', 'Sede 10')

INSERT INTO Usuario VALUES('Pepe Vaticano', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Carlos Nombe', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Primiciero Calvo', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Martin Elias', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Brayan Vladimir', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Maritza Avenllaneda', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Marcela Catalan', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Alcocer Segundo', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Alvarado Abudinen', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Yeraldine Abrias', 1, 'Correo@correo.com', '101020201')
INSERT INTO Usuario VALUES('Karol Gomez', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Vicente Ferrari', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Ariel Sirenosa', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Reynel Leon', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Marco Polo', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Simon Bolibia', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Marta Santa', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Fry Andres', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Joe Calderon', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Thomas Suarez', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Amador Romero', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Marcarlos Gonzales', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Fortunato Montes', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Luz Marina', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Angel Jose', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Gregorio Morales', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Miranda Martinez', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))
INSERT INTO Usuario VALUES('Horacio Aleman', 1, 'Correo@correo.com', CONVERT(varchar(50), Round(RAND() * 700004, 0)))

INSERT INTO Veterinario VALUES(1)
INSERT INTO Veterinario VALUES(2)
INSERT INTO Veterinario VALUES(3)
INSERT INTO Veterinario VALUES(4)
INSERT INTO Veterinario VALUES(5)
INSERT INTO Veterinario VALUES(6)
INSERT INTO Veterinario VALUES(7)
INSERT INTO Veterinario VALUES(8)
INSERT INTO Veterinario VALUES(9)
INSERT INTO Veterinario VALUES(10)
INSERT INTO Veterinario VALUES(11)
INSERT INTO Veterinario VALUES(12)
INSERT INTO Veterinario VALUES(13)
INSERT INTO Veterinario VALUES(14)
INSERT INTO Veterinario VALUES(15)
INSERT INTO Veterinario VALUES(16)


INSERT EspecialidadesXVeterinario VALUES(1,1,1)
INSERT EspecialidadesXVeterinario VALUES(2,1,1)
INSERT EspecialidadesXVeterinario VALUES(1,2,1)
INSERT EspecialidadesXVeterinario VALUES(2,3,1)
INSERT EspecialidadesXVeterinario VALUES(5,3,1)
INSERT EspecialidadesXVeterinario VALUES(4,4,1)
INSERT EspecialidadesXVeterinario VALUES(1,5,1)
INSERT EspecialidadesXVeterinario VALUES(2,5,1)
INSERT EspecialidadesXVeterinario VALUES(3,6,1)
INSERT EspecialidadesXVeterinario VALUES(4,7,1)
INSERT EspecialidadesXVeterinario VALUES(5,8,1)
INSERT EspecialidadesXVeterinario VALUES(5,9,1)
INSERT EspecialidadesXVeterinario VALUES(4,8,1)
INSERT EspecialidadesXVeterinario VALUES(3,9,1)
INSERT EspecialidadesXVeterinario VALUES(2,10,1)
INSERT EspecialidadesXVeterinario VALUES(1,11,1)
INSERT EspecialidadesXVeterinario VALUES(5,11,1)
INSERT EspecialidadesXVeterinario VALUES(3,12,1)
INSERT EspecialidadesXVeterinario VALUES(4,13,1)
INSERT EspecialidadesXVeterinario VALUES(5,12,1)
INSERT EspecialidadesXVeterinario VALUES(5,14,1)
INSERT EspecialidadesXVeterinario VALUES(4,15,1)
INSERT EspecialidadesXVeterinario VALUES(3,16,1)
INSERT EspecialidadesXVeterinario VALUES(2,15,1)